name: Build and Run Docker container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest

    env:
      DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Verify Secret Access
        run: |
          echo "DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}"
      
      - name: Build Docker image
        id: build-image
        run: |
          docker build -t my-docker-image:latest .
      
      - name: Run Docker container
        id: run-container
        run: |
          docker run DBT_ACCESS_TOKEN=$DBT_ACCESS_TOKEN my-docker-image:latest