name: Build and Run Docker container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest

    env:
      DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ steps.buildx.outputs.docker_buildx_output }}/my-docker-image:latest
      
      - name: Run Docker container
        id: run-container
        run: |
          docker run -it ${{ steps.build-image.outputs.docker_buildx_output }}/my-docker-image:latest