name: Build and Run Docker container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest

    env:
      DBT_ACCESS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v3
        run: |
          docker build -t my-docker-image:latest .
        with:
          context: .
          file: Dockerfile
          push: false
      
      - name: Run Docker container
        id: run-container
        run: |
          docker run -it my-docker-image:latest